### PR TITLE
Updated homepage UI

### PR DESCRIPTION
**Pull request by sshsrn**
Signed-off-by: SRIHARI S <sshsrn@gmail.com>

### CODE REVIEW

**Comment by sshsrn** [comment]
Fixes:
image
The green color makes the text clearly visible now.

image
As I added a background color of white with opacity too, the copyright text is also clearly visible now.

**Comment by sshsrn** [comment]
@adityabindu Kindly check!

**Comment by Kirankp25** [comment]
hey @SSHSRN you can add a hover effect for the "BOOK NOW" Button on the home page and 
for copyright add-footer for this site

**Comment by sshsrn** [comment]
I have updated it now!
@Kirankp25 Kindly check!

**Pull request closed without merging**
